services:
#  # SpringBoot
#  neuro-bridge-server:
#    container_name: handscope-server
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      neuro-bridge-db:
#        condition: service_healthy

  # MySQL
  neuro-bridge-db:
    container_name: handscope-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping"]
#      interval: 5s
#      retries: 10

