spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/handscope
    username: root
    password: neuro123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  # schema.sql / data.sql
  sql:
    init:
      mode: always

  # .env import
  config:
    import: optional:file:.env[.properties]

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC              # API 그룹 순서 → 내림차순 정렬
    tags-sorter: alpha              # 태그 정렬 방식 (alpha=알파벳순)
    operations-sorter: method       # API 메서드 정렬 방식 (method=HTTP 메서드 순)
    display-request-duration: true  # 요청 시간 표시 (추가 옵션)
    doc-expansion: none             # 초기 Swagger UI에서 API 문서 열림 상태 (none/ list/ full)
    persist-authorization: true     # 토큰 입력값 유지 여부 (페이지 새로고침 시 유지)
  api-docs:
    enabled: true

#JWT TOKEN
jwt:
  secret: ${SECRET_KEY}
  token-validity-in-seconds: 86400  # 24시간


# OpenAI API
openai:
  api:
    key: ${OPENAI_API_KEY}
